hydra:
  run:
    dir: ${compute_workdir:${deriva_ml.working_dir},${deriva_ml.catalog_id}}/hydra/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: hydra-config
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - experiments=cifar10_quick,cifar10_extended
    - datasets=cifar10_small_training
  job:
    name: _implementations
    chdir: null
    override_dirname: datasets=cifar10_small_training,experiments=cifar10_quick,cifar10_extended
    id: ???
    num: ???
    config_name: deriva_model
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: /Users/carl/GitHub/deriva-ml-model-template
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: hydra_zen.wrapper
      schema: pkg
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      model_config: default_model
      workflow: default_workflow
      assets: default_asset
      datasets: cifar10_small_training
      deriva_ml: default_deriva
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
_target_: __main__.run_model
deriva_ml:
  _target_: deriva_ml.core.config.DerivaMLConfig
  hostname: localhost
  catalog_id: 2
  domain_schema: null
  project_name: null
  cache_dir: null
  working_dir: null
  hydra_runtime_output_dir: null
  ml_schema: deriva-ml
  logging_level: 30
  deriva_logging_level: 30
  credential: null
  s3_bucket: null
  use_minid: false
  check_auth: true
datasets:
- rid: 3JHT
  version: 0.2.0
  materialize: true
  description: ''
  _target_: deriva_ml.dataset.aux_classes.DatasetSpec
assets: []
workflow:
  _target_: deriva_ml.execution.workflow.Workflow
  name: CIFAR-10 2-Layer CNN
  workflow_type: Image Classification
  description: 'Train a 2-layer convolutional neural network on CIFAR-10 image data.


    ## Architecture

    - **Conv Layer 1**: 3 → 32 channels, 3×3 kernel, ReLU, MaxPool 2×2

    - **Conv Layer 2**: 32 → 64 channels, 3×3 kernel, ReLU, MaxPool 2×2

    - **FC Layer**: 64×8×8 → 128 hidden units → 10 classes


    ## Features

    - Configurable architecture (channel sizes, hidden units, dropout)

    - Training with Adam optimizer and cross-entropy loss

    - Automatic data loading from DerivaML datasets via `restructure_assets()`

    - Outputs: model weights (`.pt`) and training log


    ## Expected Performance

    ~60-70% test accuracy with default parameters on CIFAR-10.'
  url: null
  version: null
  rid: null
  checksum: null
  is_notebook: false
  git_root: null
model_config:
  _target_: models.cifar10_cnn.cifar10_cnn
  _partial_: true
  conv1_channels: 32
  conv2_channels: 64
  hidden_size: 128
  dropout_rate: 0.0
  learning_rate: 0.001
  epochs: 10
  batch_size: 64
  weight_decay: 0.0
  label_column: Label
  ml_instance: null
  execution: null
description: Simple model run
dry_run: false
